### ISSUE TITLE
No notification... 

### ISSUE THREAD

**Issue by Y0lan** [loki-project/session-android#280]
**Describe the bug**

I have to open the app to see the new message, and I don't get notification when a new message arrive, or a new user message me. 

**Smartphone (please complete the following information):**

 - Device: One plus 8 pro
 - OS: Android 10
 - Version of Session : 1.4.1

**Comment by schattenpanzer** [comment]
Similar phone, similar os. Notifications won't come in unless I open the app. I could press home and leave it running to receive messages, but otherwise it doesn't do it on its own. [Conversations'](https://github.com/inputmice/Conversations) solution for this, is to keep it running as a background process (uses battery, but doesn't seem to use *that* much)

**Comment by schattenpanzer** [comment]
same problem with a galaxy phone running android 8, only gets notifications when the app is in the foreground

**Comment by KeeJef** [comment]
We're going to redress this shortly, cutting down on the complexity of the current system and improving Push notifications. We recognize that this is a very important feature

**Comment by fleapower** [comment]
I installed Session on an old Moto G3 with Lineage 17.1.  Session notifications work perfectly.  I've also noticed that Android One phones seem to have problems with notifications more so than other phones.

**Comment by depewzhang** [comment]
Is this issue resolved?  I'm using Samsung Galaxy S10, Android 11, with the same problem of notification.  Someone please help.

**Comment by KeeJef** [comment]
Notifications should be working reliably if you are hooked up to the "Fast Notification" mode which uses Firebase. Notifications from the slow system use background polling which is somewhat unreliable

**Comment by fleapower** [comment]
I'm still having issues with notifications.  I'm using "Fast Notification."  Nokia 6.1, Android 10.

**Comment by KeeJef** [comment]
can you explain what issues you are having?

**Comment by fleapower** [comment]
No changes from the previous posts (not being snarky...I didn't expect you to ready them):

"Nokia 6.1 2018 using Android 10. I've tried both methods of notification (Google push and Session pull). Neither are reliable. Notifications only work when the app is in the foreground. I've turned off battery optimization for Session."

"I installed Session on an old Moto G3 with Lineage 17.1. Session notifications work perfectly. I've also noticed that Android One phones seem to have problems with notifications more so than other phones."

**Comment by KeeJef** [comment]
Hmmmm the fact that the same issue isn't occurring with your other device seems to point towards some sort of device deviation, there seems to a topic here which indicates issues https://community.phones.nokia.com/discussion/58594/notifications-not-working . One of the user mentions that this is happening when apps are installed from the Google Play store, perhaps you could try installing the APK directly from the Session releases page here https://github.com/oxen-io/session-android/releases/tag/1.7.4

**Comment by fleapower** [comment]
> Hmmmm the fact that the same issue isn't occurring with your other device seems to point towards some sort of device deviation, there seems to a topic here which indicates issues https://community.phones.nokia.com/discussion/58594/notifications-not-working . One of the user mentions that this is happening when apps are installed from the Google Play store, perhaps you could try installing the APK directly from the Session releases page here https://github.com/oxen-io/session-android/releases/tag/1.7.4

Thanks for the suggestion.  Just tried it.  No luck.

**Comment by knowpwr** [comment]
Facing the same situation here with TCL 10L (Android 10) phone. Notification works for all apps (including Signal) excluding Session. Session is put on safe list of apps to start whenever. Battery optimization is disabled for Session. It would be really awesome if you revisit the notification feature to fix this issue. Thank you.
